language: node_js
node_js:
  - iojs
sudo: false
cache:
  directories:
    - src/client/node_modules
    - src/client/bower_components
    - $HOME/.nvm
before_install:
  - npm install -g bower gulp
install:
  - cd src/client && npm install && bower install
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 2
script:
  - cd src/client && gulp protractor
