- hosts: all
  tasks:
    - name: ensure packages are installed and up to date
      apt: pkg={{item}} state=latest update_cache=yes
      notify:
      - restart postgresql
      with_items:
      - postgresql
      - nginx
      - uwsgi
      - uwsgi-plugin-python3
      - python3
      - python3-flask
      - python3-flask-sqlalchemy
      - python3-requests
      - python-psycopg2
      - python3-psycopg2

    - name: ensure application group exists
      group: name=hieronymus

    - name: ensure application user exists
      user: name=hieronymus group=hieronymus

    - name: ensure application directory exists
      file: path=/var/lib/hieronymus state=directory owner=hieronymus group=hieronymus mode=0740

    - name: copy local source tree
      synchronize: src=../src/ dest=/var/lib/hieronymus/ rsync_path="sudo rsync"
      notify:
      - restart app

    - name: install uwsgi app config
      copy: src=target/hieronymus-uwsgi.ini dest=/etc/uwsgi/hieronymus.ini mode=0644 owner=root group=root
      notify:
      - restart app

    - name: install uwsgi app upstart script
      copy: src=target/hieronymus-upstart.conf dest=/etc/init/hieronymus.conf mode=0644 owner=root group=root
      notify:
      - restart app

    - name: create app uwsgi socket dir
      file: path=/run/uwsgi/hieronymus state=directory owner=www-data group=www-data mode=0740

    - name: install nginx config
      copy: src=target/nginx-node.conf dest=/etc/nginx/sites-available/default mode=0644 owner=root group=root
      notify:
      - restart nginx

    - name: ensure postgresql starts on boot
      service: name=postgresql enabled=yes
      notify:
      - restart postgresql

    - name: ensure nginx starts on boot
      service: name=nginx enabled=yes
      notify:
      - restart nginx
  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted

    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart app
      service: name=hieronymus state=restarted

    - name: sync back
      synchronize: dest=../src src=/var/lib/hieronymus mode=pull rsync_path="sudo rsync"

- hosts: all
  sudo: yes
  sudo_user: postgres
  tasks:
    - name: create postgresql cluster
      shell: pg_createcluster --start 9.3 main
      args:
        creates: /var/lib/postgresql/9.3/main

    - name: create app db
      postgresql_db: name=hieronymus

    - name: create abb db user
      postgresql_user: db=hieronymus name=hieronymus password=2dS3v5l6oaG2RpEne1CH7WT9UyEwe5nk

- hosts: all
  tasks:
    - name: initialize app db
      command: python3 /var/lib/hieronymus/server/server.py --create-db

    - name: ensure app starts on boot
      service: name=hieronymus enabled=yes

    - name: ensure app is running
      service: name=hieronymus state=running
